export const PRIVILEGES = Object.freeze({
	ADD_RESERVATION: "AddReservation",
	VIEW_RESERVATIONS_PERSONAL: "ViewReservations_Personal",
	VIEW_RESERVATION_DETAILS_PERSONAL: "ViewReservationDetails_Personal",
	ADD_REFUND: "AddRefund",
	VIEW_REFUNDS_PERSONAL: "ViewRefunds_Personal",
	VIEW_REFUND_DETAILS_PERSONAL: "ViewRefundDetails_Personal",
	VIEW_CURRENT_CAMPING_SEASON: "ViewCurrentCampingSeason",
	VIEW_RESERVATIONS: "ViewReservations",
	MANAGE_RESERVATIONS: "ManageReservations",
	VIEW_RESERVATION_DETAILS: "ViewReservationDetails",
	MANAGE_REFUNDS: "ManageRefunds",
	VIEW_REFUNDS: "ViewRefunds",
	VIEW_REFUNDS_DETAILS: "ViewRefundsDetails",
	MANAGE_CAMPING_SEASONS: "ManageCampingSeasons",
	VIEW_CAMPING_SEASONS: "ViewCampingSeasons",
	VIEW_CAMPING_SEASON_DETAILS: "ViewCampingSeasonDetails",
	MANAGE_USERS: "ManageUsers",
	VIEW_USERS: "ViewUsers",
	VIEW_USER_DETAILS: "ViewUserDetails",
	MANAGE_ROLES: "ManageRoles",
	VIEW_ROLES: "ViewRoles",
	VIEW_ROLE_DETAILS: "ViewRoleDetails",
	MANAGE_SYSTEM_CONFIGURATIONS: "ManageSystemConfigurations",
	VIEW_SYSTEM_CONFIGURATIONS: "ViewSystemConfigurations",
	VIEW_SYSTEM_CONFIGURATIONS_DETAILS: "ViewSystemConfigurationsDetails",
	VIEW_REFUNDS_GOVERNORATE: "ViewRefunds_Governorate",
	VIEW_REFUNDS_DETAILS_GOVERNORATE: "ViewRefundsDetails_Governorate",
	MANAGE_REFUNDS_GOVERNORATE: "ManageRefunds_Governorate",
	CAN_ACCESS_ADMIN: "CanAccessAdmin",
  VIEW_RESERVATIONS_GOVERNORATE: "ViewReservations_Governorate",
  VIEW_RESERVATION_DETAILS_GOVERNORATE: "ViewReservationDetails_Governorate",
});

export type PrivilegeCode = typeof PRIVILEGES[keyof typeof PRIVILEGES];
