const RESERVATION_STATUS = Object.freeze({
	PENDING_PAYMENT: 1,
	PAID_AND_LICENSED: 2,
	REFUND_REQUEST_PENDING_INSPECTOR: 3,
	REFUND_REQUEST_PENDING_FINANCE: 6,
	LICENSE_CANCELLED: 7,
	FEES_REFUNDED: 8,
	INCOMPLETE: 9,
	REFUND_REQUEST_PENDING_VIOLATION_REMOVAL: 10,
	REFUND_REQUEST_PENDING_IBAN_UPDATE: 11,
	REFUND_REQUEST_IN_PROCESS: 12
});

export { RESERVATION_STATUS };