const FEATURE_TYPE = Object.freeze({
	GOVERNORATE: "Governorate",
	NEIGHBORHOOD: "Neighborhood",
	BLOCK: "Block",
	STREET: "Street",
	PARCEL: "Parcel",
	LANDMARK: "Landmark",
	GEOCODER: "Geocoder",
});

const SEARCH_LAYER = Object.freeze({
	GOVERNORATE: 3,
	NEIGHBORHOOD: 2,
	BLOCK: 1,
	STREET: 0,
	LANDMARK: 4,
});

const SEARCH_LAYER_FEATURE_TYPE_MAPPING = Object.freeze(
	new Map([
		[SEARCH_LAYER.GOVERNORATE, FEATURE_TYPE.GOVERNORATE],
		[SEARCH_LAYER.NEIGHBORHOOD, FEATURE_TYPE.NEIGHBORHOOD],
		[SEARCH_LAYER.BLOCK, FEATURE_TYPE.BLOCK],
		[SEARCH_LAYER.STREET, FEATURE_TYPE.STREET],
		[SEARCH_LAYER.LANDMARK, FEATURE_TYPE.LANDMARK],
	])
);

export { FEATURE_TYPE, SEARCH_LAYER, SEARCH_LAYER_FEATURE_TYPE_MAPPING };
